src/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from hello.views import index
from contacts.views import contacts
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', index),
    path('contacts', contacts),
    path('directory/', include('dimensionsapp.dimurl')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/goodsapp/models.py
from django.db import models
from dimensionsapp import models as referen

# Create your models here.


class Book(models.Model):
    name = models.CharField("Название книги", max_length=200)
    image_field = models.ImageField("Фото обложки", blank=True, null=True, upload_to='bookimage')
    price = models.DecimalField("Цена (BYN)", max_digits=8, decimal_places=2)
    authors = models.ManyToManyField(referen.Author, verbose_name="Авторы")
    serie = models.ForeignKey(referen.Serie, on_delete=models.PROTECT, verbose_name="Серия", null=True, blank=True)
    jenre = models.ManyToManyField(referen.Jenre, verbose_name="Жанры")
    year_publishing = models.PositiveIntegerField("Год издания")
    count_pages = models.PositiveIntegerField("Количество страниц")
    binding = models.ForeignKey(referen.Binding, on_delete=models.PROTECT, verbose_name="Переплет")
    format_book = models.ForeignKey(referen.FormatBook, on_delete=models.PROTECT, verbose_name="Формат")
    isbn = models.CharField("ISBN", max_length=13)
    weight = models.FloatField("Вес (гр)")
    age_restrictions = models.ForeignKey(referen.AgeRestriction, verbose_name="Возрастные ограничения",
                                         on_delete=models.PROTECT, )
    publisher = models.ForeignKey(referen.PublishingHouse, on_delete=models.PROTECT, verbose_name="Издательство")
    count_books = models.PositiveIntegerField("Количество книг в наличии")
    is_active = models.BooleanField("Активный (доступен для заказа)", default=True)
    rate = models.FloatField("Рейтинг")
    date_create = models.DateTimeField("Дата внесения в каталог", auto_now_add=True, )
    date_update = models.DateTimeField("Дата последнего изменения карточки", auto_now=True)

    def description(self):
        return ', '.join([str(s) for s in self.authors.all()]) + " \"" + self.name + "\""

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "книга"
        verbose_name_plural = "книги"


class Menu(models.Model):
    name = models.CharField("Пункт меню", max_length=30, unique=True)
    url_name = models.CharField("Название ссылки", max_length=100)
    parent_menu = models.ForeignKey('Menu', on_delete=models.PROTECT, related_name='parent_menu_item',
                                    related_query_name='parent_menu_item', null=True, blank=True)

    def __str__(self):
        return self.name

src/goodsapp/views.py
from django.shortcuts import render
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from .models import Menu, Book
# Create your views here.


class MenuList(ListView):
    queryset = Menu.objects.filter(parent_menu__isnull=True)


class BookListView(ListView):
    model = Book


class BookDetailView(DetailView):
    model = Book

src/templates/goodsapp/book_detail.html
{% extends 'dimension_detail.html' %}
{% block title %}
  Книга {{ object.description }}
{% endblock %}

{% block to_list %}
    <a href="{% url 'book_list' %}">Все книги</a>
{% endblock %}



{% block dimension %}
    <h3>{{ object.description }}</h3>
    <div class="image-container" >
        {% if object.image_field %}
            <img src="{{ object.image_field.url }}" alt="{{ object.description }}" style="max-width: 250px;">
        {% else %}
            <p>Без фото</p>
        {% endif %}

        <p><b>Цена: {{ object.price }} руб.</b></p>
    </div>
    <div>
        <p><strong>Название:</strong> {{ object.name }}</p>
        <p><strong>Авторы:</strong>
            {% for  author  in object.authors.all%}
                <a href="{% url 'author_detail' author.pk %}">{{ author.name }}</a>
            {% endfor %}
            </p>
        <p><strong>Серия:</strong> {{ object.serie|default_if_none:"Не указана" }}</p>
        <p><strong>Жанры:</strong>
            {% for jenre in object.jenre.all %}
                <a href="{% url 'jenre_detail' jenre.pk %}">{{ jenre.name }}</a>
            {% endfor %}
            </p>
        <p><strong>Год издания:</strong> {{ object.year_publishing }}</p>
        <p><strong>Количество страниц:</strong> {{ object.count_pages }}</p>
        <p><strong>Переплет:</strong> {{ object.binding }}</p>
        <p><strong>Формат:</strong> {{ object.format_book }}</p>
        <p><strong>ISBN:</strong> {{ object.isbn }}</p>
        <p><strong>Вес:</strong> {{ object.weight }} гр</p>
        <p> {{ object.age_restriction }}</p>
        <p><strong> {{ object.is_active|yesno:"Есть на складе,Нет на складе" }}</strong></p>
        <p><strong>Рейтинг:</strong> {{ object.rate }}</p>
    </div>

{% endblock %}

src/templates/goodsapp/book_list.html
{% extends 'dimension_list.html' %}

{% block title %}
    Книги
{% endblock %}

{% block header %}
        <H1>Книги</H1>
{% endblock %}

{% block searchform %}
{% endblock %}

{% block dimension_list %}
            <tr>
                <th>Наименование</th>
                <th>Цена</th>
            </tr>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'book_detail' object.pk %}">{{ object.description }}</a></td>
                    <td>{{  object.price }}</td>
                </tr>
            {% endfor %}
        {% endblock %}

src/templates/goodsapp/menu_list.html
<nav>
<ul>
    {% for menu in menu_list %}
        <li><a href="{% url menu.url_name %}">{{ menu.name }}</a></li>
    {% endfor %}
</ul>
</nav>

src/templates/goodsapp/menu_view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Справочники</title>
</head>
<body>
    {% include 'menu.html' %}
</body>
</html>