src/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from hello.views import index
from contacts.views import contacts
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('hello/', index),
    path('contacts', contacts),
    path('directory/', include('dimensionsapp.dimurl')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/dimensionsapp/models.py
from django.db import models
from django.urls import reverse_lazy

# Create your models here.


class Dimension(models.Model):
    name = models.CharField("Наименование", max_length=50, unique=True)
    description = models.TextField("Описание", blank=True, )

    def __str__(self):
        return self.name

    class Meta:
        abstract = True
        ordering = ['name']


class Author(Dimension):
    biography = models.TextField("Биография", blank=True, )

    def get_absolute_url(self):
        return reverse_lazy('author_detail', args=[self.pk])

    class Meta(Dimension.Meta):
        verbose_name = 'автор'
        verbose_name_plural = 'авторы'


class Serie(Dimension):
    def get_absolute_url(self):
        return reverse_lazy('serie_detail', args=[self.pk, ])

    class Meta(Dimension.Meta):
        verbose_name = 'серия'
        verbose_name_plural = 'серии'


class Jenre(Dimension):
    def get_absolute_url(self):
        return reverse_lazy('jenre_detail', args=[self.pk])

    class Meta(Dimension.Meta):
        verbose_name = 'жанр'
        verbose_name_plural = 'жанры'


class PublishingHouse(Dimension):
    def get_absolute_url(self):
        return reverse_lazy('publishing_house_detail', args=[self.pk])

    class Meta(Dimension.Meta):
        verbose_name = 'издательство'
        verbose_name_plural = 'издательства'


class FormatBook(Dimension):
    def get_absolute_url(self):
        return reverse_lazy('format_book_detail', args=[self.pk])

    class Meta(Dimension.Meta):
        verbose_name = 'формат'
        verbose_name_plural = 'форматы'


class Binding(Dimension):
    def get_absolute_url(self):
        return reverse_lazy('binding_detail', args=[self.pk])

    class Meta(Dimension.Meta):
        verbose_name = 'переплет'
        verbose_name_plural = 'переплеты'


class AgeRestriction(Dimension):
    def get_absolute_url(self):
        return reverse_lazy('age_restriction_detail', args=[self.pk])

    class Meta(Dimension.Meta):
        verbose_name = "возрастное ограничение"
        verbose_name_plural = "возрастные ограничения"
        ordering = ['description']

src/dimensionsapp/views.py
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView
from dimensionsapp.models import Author, Serie, Jenre, PublishingHouse, FormatBook, Binding, \
    AgeRestriction
from dimensionsapp.form import SearchFormAuthor, AuthorModel, JenreModel, SerieModel, \
    PublishingHouseModel, FormatBookModel, BindingModel, AgeRestrictionModel, SearchForm
from django.views.generic import TemplateView, ListView
from django.urls import reverse_lazy
# from goodsapp.models import Menu
# Create your views here.


class AuthorDetailView(DetailView):
    model = Author


class SerieDetailView(DetailView):
    model = Serie


class JenreDetailView(DetailView):
    model = Jenre


class PublishingHouseDetailView(DetailView):
    model = PublishingHouse


class FormatBookDetailView(DetailView):
    model = FormatBook


class BindingDetailView(DetailView):
    model = Binding


class AgeRestrictionDetailView(DetailView):
    model = AgeRestriction


class ListViewFilter(ListView):
    form = SearchForm
    paginate_by = 25

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        if 'search' in self.request.GET:
            context['form'] = self.form({'search': self.request.GET['search']})
        else:
            context['form'] = self.form()
        return context

    def get_queryset(self):
        qs = super().get_queryset()
        if 'search' in self.request.GET and self.request.GET['search'] != '':
            name = self.request.GET['search']
            qs = qs.filter(name__istartswith=name)
        return qs


class SerieListView(ListViewFilter):
    model = Serie
    extra_context = {'url_detail': 'serie_detail'}


class JenreListView(ListViewFilter):
    model = Jenre
    extra_context = {'url_detail': 'jenre_detail'}


class PublishingHouseListView(ListViewFilter):
    model = PublishingHouse
    extra_context = {'url_detail': 'publishing_house_detail'}

    # def get_context_data(self, *, object_list=None, **kwargs):
    #     context = super().get_context_data(**kwargs)
    #     context['url_detail'] = 'publishing_house_detail'
    #     return context


class FormatBookListView(ListViewFilter):
    model = FormatBook
    extra_context = {'url_detail': 'format_book_detail'}


class BindingListView(ListViewFilter):
    model = Binding
    extra_context = {'url_detail': 'binding_detail', }


class AgeRestrictionListView(ListViewFilter):
    model = AgeRestriction
    extra_context = {'url_detail': 'age_restriction_detail'}


class AuthorListView(ListViewFilter):
    model = Author
    form = SearchFormAuthor
    extra_context = {'url_detail': 'author_detail'}


class MenuView(TemplateView):
    template_name = 'goodsapp/menu_view.html'


class SerieCreateView(CreateView):
    model = Serie
    form_class = SerieModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('serie_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('serie_detail', kwargs={'pk': self.object.pk})
        return url


class AuthorCreateView(CreateView):
    model = Author
    form_class = AuthorModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('author_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('author_detail', kwargs={'pk': self.object.pk})
        return url


class JenreCreateView(CreateView):
    model = Jenre
    form_class = JenreModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('jenre_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('jenre_detail', kwargs={'pk': self.object.pk})
        return url


class PublishingHouseCreateView(CreateView):
    model = PublishingHouse
    form_class = PublishingHouseModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('publishing_house_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('publishing_house_detail', kwargs={'pk': self.object.pk})
        return url


class FormatBookCreateView(CreateView):
    model = FormatBook
    form_class = FormatBookModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('format_book_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('format_book_detail', kwargs={'pk': self.object.pk})
        return url


class BindingCreateView(CreateView):
    model = Binding
    form_class = BindingModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('binding_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('binding_detail', kwargs={'pk': self.object.pk})
        return url


class AgeRestrictionCreateView(CreateView):
    model = AgeRestriction
    form_class = AgeRestrictionModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('age_restriction_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('age_restriction_detail', kwargs={'pk': self.object.pk})
        return url


class SerieUpdateView(UpdateView):
    model = Serie
    form_class = SerieModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('serie_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('serie_detail', kwargs={'pk': self.object.pk})
        return url


class AuthorUpdateView(UpdateView):
    model = Author
    form_class = AuthorModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('author_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('author_detail', kwargs={'pk': self.object.pk})
        return url


class JenreUpdateView(UpdateView):
    model = Jenre
    form_class = JenreModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('jenre_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('jenre_detail', kwargs={'pk': self.object.pk})
        return url


class PublishingHouseUpdateView(UpdateView):
    model = PublishingHouse
    form_class = PublishingHouseModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('publishing_house_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('publishing_house_detail', kwargs={'pk': self.object.pk})
        return url


class FormatBookUpdateView(UpdateView):
    model = FormatBook
    form_class = FormatBookModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('format_book_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('format_book_detail', kwargs={'pk': self.object.pk})
        return url

    def post(self, request, *args, **kwargs):
        result = super().post(request, *args, **kwargs)
        if 'save-as' in self.request.POST.keys() and 'pk' in kwargs.keys():
            print(self.object)
        return result


class BindingUpdateView(UpdateView):
    model = Binding
    form_class = BindingModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('binding_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('binding_detail', kwargs={'pk': self.object.pk})
        return url


class AgeRestrictionUpdateView(UpdateView):
    model = AgeRestriction
    form_class = AgeRestrictionModel

    def get_success_url(self):
        url = super().get_success_url()
        if 'save-and-close' in self.request.POST.keys():
            url = reverse_lazy('age_restriction_list')
        elif 'save' in self.request.POST.keys():
            url = reverse_lazy('age_restriction_detail', kwargs={'pk': self.object.pk})
        return url

src/templates/dimensionsapp/agerestriction_detail.html
{% extends 'dimension_detail.html' %}
{% block title %}
  Возрастное ограничение {{ object.name }}
{% endblock %}

{% block to_list %}
    <a href="{% url 'age_restriction_list' %}">Все возрастные ограничения</a>
{% endblock %}

{% block page_name %}
        Возрастное ограничение
      {% endblock %}

{% block dimension %}
    {% include "dimension_template.html" %}
{% endblock %}

{% block update_url %}{% url 'age_restriction_update' object.pk%}{% endblock %}

src/templates/dimensionsapp/agerestriction_form.html
{% extends 'dimension_create.html' %}

{% block title %}
    Возрастное ограничение
{% endblock %}

{% block maincaption %}Возрастное ограничение{% endblock %}

{% block to_list %}

{% endblock %}

{% block saveas_url %}{% url 'age_restriction_book_create' %}{% endblock %}

src/templates/dimensionsapp/agerestriction_list.html
{% extends 'dimension_list.html' %}

{% block title %}
    Возрастные ограничения
{% endblock %}

{% block header %}
        <H1>Ограничения по возрасту</H1>
    {% endblock %}

{% block create_ankor%}{% url 'age_restriction_create' %}{% endblock %}

src/templates/dimensionsapp/author_detail.html
{% extends 'dimension_detail.html' %}
{% block title %}
  Автор {{ object.name }}
{% endblock %}

{% block to_list %}
    <a href="{% url 'author_list' %}">Все авторы</a>
{% endblock %}

{% block page_name %}
         Автор
      {% endblock %}

{% block dimension %}
    {% include "dimension_template.html" %}
    <p><strong>Биография:</strong> {{ object.biography }}</p>
{% endblock %}

{% block update_url %}{% url 'author_update' object.pk%}{% endblock %}

src/templates/dimensionsapp/author_list.html
{% extends 'dimension_list.html' %}

{% block title %}
    Авторы
{% endblock %}
{% block create_ankor%}{% url 'author_create' %}{% endblock %}
{% block dimension_list %}
            <tr>
                <th>Имя</th>
                <th>Описание</th>
                <th>Биография</th>
            </tr>
            {% for object in object_list %}
                <tr>
                    <td><a href="{% url 'author_detail' object.pk %}">{{ object.name }}</a></td>
                    <td>{{  object.description }}</td>
                    <td>{{ object.biography }}</td>
                </tr>
            {% endfor %}
{% endblock %}

{% block header %}
        <H1>Авторы</H1>
{% endblock %}

src/templates/dimensionsapp/binding_form.html
{% extends 'dimension_create.html' %}

{% block title %}
    Переплет
{% endblock %}
{% block maincaption %}Переплет{% endblock %}
{% block to_list %}

{% endblock %}

{% block saveas_url %}{% url 'binding_create' %}{% endblock %}

src/templates/dimensionsapp/formatbook_form.html
{% extends 'dimension_create.html' %}

{% block title %}
    Формат
{% endblock %}

{% block maincaption %}Формат{% endblock %}

{% block to_list %}

{% endblock %}

{% block saveas_url %}{% url 'format_book_create' %}{% endblock %}

src/templates/dimensionsapp/jenre_detail.html
{% extends 'dimension_detail.html' %}
{% block title %}
  Жанр {{ object.name }}
{% endblock %}

{% block to_list %}
    <a href="{% url 'jenre_list' %}">Все жанры</a>
{% endblock %}

{% block page_name %}
        Жанр
      {% endblock %}

{% block dimension %}
    {% include "dimension_template.html" %}
{% endblock %}

{% block update_url %}{% url 'jenre_update' object.pk%}{% endblock %}

src/templates/dimensionsapp/jenre_form.html
{% extends 'dimension_create.html' %}

{% block title %}
    Жанр
{% endblock %}

{% block maincaption %}Жанр{% endblock %}
{% block to_list %}

{% endblock %}

{% block saveas_url %}{% url 'jenre_create' %}{% endblock %}

src/templates/dimensionsapp/jenre_list.html
{% extends 'dimension_list.html' %}

{% block title %}
    Жанры
{% endblock %}

{% block header %}
        <H1>Жанры</H1>
    {% endblock %}

{% block create_ankor%}{% url 'jenre_create' %}{% endblock %}

src/templates/dimensionsapp/main_menu.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Меню справочников</title>
</head>
<body>
 {% include 'menu.html' %}
</body>
</html>

src/templates/dimensionsapp/publishinghouse_detail.html
{% extends 'dimension_detail.html' %}
{% block title %}
  Издательство {{ object.name }}
{% endblock %}

{% block to_list %}
    <a href="{% url 'publishing_house_list' %}">Все издательства</a>
{% endblock %}

{% block page_name %}
        Издательство
      {% endblock %}

{% block dimension %}
    {% include "dimension_template.html" %}
{% endblock %}

{% block update_url %}{% url 'publishing_house_update' object.pk%}{% endblock %}

src/templates/dimensionsapp/publishinghouse_form.html
{% extends 'dimension_create.html' %}

{% block title %}
    Издательство
{% endblock %}
{% block maincaption %}Издательство{% endblock %}

{% block to_list %}

{% endblock %}

{% block saveas_url %}{% url 'publishing_house_create' %}{% endblock %}

src/templates/dimensionsapp/serie_detail.html
{% extends 'dimension_detail.html' %}
{% block title %}
  Серия {{ object.name }}
{% endblock %}

{% block to_list %}
    <a href="{% url 'serie_list' %}">Все серии</a>
{% endblock %}

{% block page_name %}
        Серия
      {% endblock %}

{% block dimension %}
    {% include "dimension_template.html" %}
{% endblock %}

{% block update_url %}{% url 'serie_update' object.pk%}{% endblock %}